# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preset_editor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 660)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPlainTextEdit {\n"
"    font-family: \"Lucida Console\",\"Courier\";\n"
"    font-size: 9pt; \n"
"    background-color: #262626;\n"
"    selection-background-color: #2e5ea4;\n"
"/*    color: #dddddd;  */\n"
"}\n"
"QWidget:focus {\n"
"    border: 1px solid #2e5ea4;\n"
"}\n"
"\n"
"QListWidget:item:selected{\n"
"background: #2e5ea4\n"
"}\n"
"\n"
"QTapWidget{\n"
"    border: 1px solid #2e5ea4;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea4; \n"
"    border: 1px solid #2e5ea4;\n"
"    color: #ffffff;\n"
"}\n"
"/*QPushButton:flat {\n"
"    background-color: #666666;\n"
"    color: #ff0000;    \n"
"    border: 1px solid #cccccc;\n"
"}\n"
"QPushButton:default {\n"
"    background-color: #ff0000;\n"
"    color: #ff0000;    \n"
"    border: 1px solid #000000;\n"
"}*/\n"
"QPushButton {\n"
"    color: #cccccc;    \n"
"    border: 1px solid #888888;\n"
"    background: #ff0000;\n"
"    padding: 2px\n"
"} \n"
"QWidget {\n"
"    background: #222222;\n"
"    color: #cccccc;\n"
"}\n"
"\n"
"QTreeView::item:has-children {\n"
"    font-weight: bold;\n"
"}\n"
"QTreeView::item:selected {\n"
"     background-color: #2e5ea4;\n"
"     color: #cccccc;\n"
"     font-weight: bold;\n"
"}\n"
"\n"
"QTreeView::branch {\n"
"    background-color: #222222;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #222222;   \n"
"    border: 2px solid #cccccc;\n"
"    border-bottom-color: #cccccc; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #2e5ea4\n"
"    }\n"
"")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nameLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.PresetIDTextBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.PresetIDTextBox.setEnabled(False)
        self.PresetIDTextBox.setObjectName("PresetIDTextBox")
        self.gridLayout_2.addWidget(self.PresetIDTextBox, 1, 4, 1, 1)
        self.detektorLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detektorLabel.sizePolicy().hasHeightForWidth())
        self.detektorLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.detektorLabel.setFont(font)
        self.detektorLabel.setObjectName("detektorLabel")
        self.gridLayout_2.addWidget(self.detektorLabel, 4, 0, 1, 1)
        self.versionTextBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.versionTextBox.setObjectName("versionTextBox")
        self.gridLayout_2.addWidget(self.versionTextBox, 4, 4, 1, 1)
        self.UniqueID = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UniqueID.sizePolicy().hasHeightForWidth())
        self.UniqueID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UniqueID.setFont(font)
        self.UniqueID.setObjectName("UniqueID")
        self.gridLayout_2.addWidget(self.UniqueID, 1, 3, 1, 1)
        self.PresetIDLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PresetIDLabel.sizePolicy().hasHeightForWidth())
        self.PresetIDLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PresetIDLabel.setFont(font)
        self.PresetIDLabel.setObjectName("PresetIDLabel")
        self.gridLayout_2.addWidget(self.PresetIDLabel, 2, 0, 2, 1)
        self.detectorBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.detectorBox.setObjectName("detectorBox")
        self.gridLayout_2.addWidget(self.detectorBox, 4, 1, 1, 1)
        self.versionLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLabel.sizePolicy().hasHeightForWidth())
        self.versionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_2.addWidget(self.versionLabel, 4, 3, 1, 1)
        self.nameBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout_2.addWidget(self.nameBox, 1, 1, 1, 2)
        self.presetIDBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.presetIDBox.setObjectName("presetIDBox")
        self.gridLayout_2.addWidget(self.presetIDBox, 2, 1, 1, 1)
        self.PresestTypeLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PresestTypeLabel.sizePolicy().hasHeightForWidth())
        self.PresestTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PresestTypeLabel.setFont(font)
        self.PresestTypeLabel.setObjectName("PresestTypeLabel")
        self.gridLayout_2.addWidget(self.PresestTypeLabel, 2, 3, 2, 1)
        self.PresetType = QtWidgets.QLineEdit(self.groupBox_5)
        self.PresetType.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PresetType.setFont(font)
        self.PresetType.setObjectName("PresetType")
        self.gridLayout_2.addWidget(self.PresetType, 2, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 3, 0, 2, 5)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_4.addWidget(self.loadButton, 2, 1, 1, 1)
        self.saveAsButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveAsButton.setAutoDefault(False)
        self.saveAsButton.setDefault(False)
        self.saveAsButton.setFlat(False)
        self.saveAsButton.setObjectName("saveAsButton")
        self.gridLayout_4.addWidget(self.saveAsButton, 2, 2, 1, 1)
        self.browseFactorySpectra = QtWidgets.QPushButton(self.centralwidget)
        self.browseFactorySpectra.setAutoDefault(False)
        self.browseFactorySpectra.setDefault(False)
        self.browseFactorySpectra.setFlat(False)
        self.browseFactorySpectra.setObjectName("browseFactorySpectra")
        self.gridLayout_4.addWidget(self.browseFactorySpectra, 2, 3, 1, 1)
        self.FactorySpectraTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.FactorySpectraTextBox.setEnabled(False)
        self.FactorySpectraTextBox.setObjectName("FactorySpectraTextBox")
        self.gridLayout_4.addWidget(self.FactorySpectraTextBox, 2, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.displayAllWLBox = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.displayAllWLBox.setFont(font)
        self.displayAllWLBox.setObjectName("displayAllWLBox")
        self.gridLayout.addWidget(self.displayAllWLBox, 4, 3, 1, 1)
        self.prefWLLabel = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefWLLabel.sizePolicy().hasHeightForWidth())
        self.prefWLLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prefWLLabel.setFont(font)
        self.prefWLLabel.setObjectName("prefWLLabel")
        self.gridLayout.addWidget(self.prefWLLabel, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.prefWLBox = QtWidgets.QComboBox(self.tab_3)
        self.prefWLBox.setObjectName("prefWLBox")
        self.gridLayout.addWidget(self.prefWLBox, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 12, 2, 1, 1)
        self.usvisibleBox = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usvisibleBox.setFont(font)
        self.usvisibleBox.setObjectName("usvisibleBox")
        self.gridLayout.addWidget(self.usvisibleBox, 3, 3, 1, 1)
        self.WLList = QtWidgets.QListWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WLList.sizePolicy().hasHeightForWidth())
        self.WLList.setSizePolicy(sizePolicy)
        self.WLList.setObjectName("WLList")
        self.gridLayout.addWidget(self.WLList, 1, 0, 5, 2)
        self.WLLabel = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WLLabel.sizePolicy().hasHeightForWidth())
        self.WLLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WLLabel.setFont(font)
        self.WLLabel.setObjectName("WLLabel")
        self.gridLayout.addWidget(self.WLLabel, 0, 0, 1, 1)
        self.addWL = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addWL.sizePolicy().hasHeightForWidth())
        self.addWL.setSizePolicy(sizePolicy)
        self.addWL.setObjectName("addWL")
        self.gridLayout.addWidget(self.addWL, 6, 0, 1, 1)
        self.removeWL = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeWL.sizePolicy().hasHeightForWidth())
        self.removeWL.setSizePolicy(sizePolicy)
        self.removeWL.setObjectName("removeWL")
        self.gridLayout.addWidget(self.removeWL, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setToolTipDuration(-1)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_8.addWidget(self.deleteButton, 8, 3, 1, 1)
        self.selectedList = QtWidgets.QListWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedList.sizePolicy().hasHeightForWidth())
        self.selectedList.setSizePolicy(sizePolicy)
        self.selectedList.setObjectName("selectedList")
        self.gridLayout_8.addWidget(self.selectedList, 6, 4, 4, 3)
        self.unselectedLabel = QtWidgets.QLabel(self.tab)
        self.unselectedLabel.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unselectedLabel.setFont(font)
        self.unselectedLabel.setObjectName("unselectedLabel")
        self.gridLayout_8.addWidget(self.unselectedLabel, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 2, 1, 1)
        self.userSoundBox = QtWidgets.QSpinBox(self.tab)
        self.userSoundBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.userSoundBox.setMinimum(-150)
        self.userSoundBox.setMaximum(150)
        self.userSoundBox.setObjectName("userSoundBox")
        self.gridLayout_8.addWidget(self.userSoundBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 3, 1, 2)
        self.addButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setToolTipDuration(-1)
        self.addButton.setObjectName("addButton")
        self.gridLayout_8.addWidget(self.addButton, 7, 3, 1, 1)
        self.backgroundOxyBox = QtWidgets.QSpinBox(self.tab)
        self.backgroundOxyBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.backgroundOxyBox.setMaximum(100)
        self.backgroundOxyBox.setObjectName("backgroundOxyBox")
        self.gridLayout_8.addWidget(self.backgroundOxyBox, 1, 5, 1, 1)
        self.selectedLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectedLabel.setFont(font)
        self.selectedLabel.setObjectName("selectedLabel")
        self.gridLayout_8.addWidget(self.selectedLabel, 5, 5, 1, 1)
        self.SFAFrameThreshBox = QtWidgets.QDoubleSpinBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SFAFrameThreshBox.setFont(font)
        self.SFAFrameThreshBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SFAFrameThreshBox.setMaximum(1.0)
        self.SFAFrameThreshBox.setSingleStep(0.01)
        self.SFAFrameThreshBox.setObjectName("SFAFrameThreshBox")
        self.gridLayout_8.addWidget(self.SFAFrameThreshBox, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 1, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.unselectedList = QtWidgets.QListWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unselectedList.sizePolicy().hasHeightForWidth())
        self.unselectedList.setSizePolicy(sizePolicy)
        self.unselectedList.setMinimumSize(QtCore.QSize(100, 300))
        self.unselectedList.setObjectName("unselectedList")
        self.gridLayout_8.addWidget(self.unselectedList, 6, 0, 4, 2)
        self.backgroundAbsorptionBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.backgroundAbsorptionBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.backgroundAbsorptionBox.setDecimals(3)
        self.backgroundAbsorptionBox.setMaximum(0.1)
        self.backgroundAbsorptionBox.setSingleStep(0.001)
        self.backgroundAbsorptionBox.setObjectName("backgroundAbsorptionBox")
        self.gridLayout_8.addWidget(self.backgroundAbsorptionBox, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 1, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 2, 0, 1, 1)
        self.maxavgframes = QtWidgets.QSpinBox(self.tab)
        self.maxavgframes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.maxavgframes.setMinimum(1)
        self.maxavgframes.setMaximum(99)
        self.maxavgframes.setProperty("value", 7)
        self.maxavgframes.setObjectName("maxavgframes")
        self.gridLayout_8.addWidget(self.maxavgframes, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 2, 3, 1, 2)
        self.sfabuffersize = QtWidgets.QSpinBox(self.tab)
        self.sfabuffersize.setMinimum(1)
        self.sfabuffersize.setObjectName("sfabuffersize")
        self.gridLayout_8.addWidget(self.sfabuffersize, 2, 5, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.enableMultiPanel = QtWidgets.QCheckBox(self.tab_2)
        self.enableMultiPanel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enableMultiPanel.setFont(font)
        self.enableMultiPanel.setChecked(True)
        self.enableMultiPanel.setObjectName("enableMultiPanel")
        self.gridLayout_11.addWidget(self.enableMultiPanel, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.view1Button = QtWidgets.QRadioButton(self.groupBox_3)
        self.view1Button.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view1Button.setFont(font)
        self.view1Button.setChecked(True)
        self.view1Button.setObjectName("view1Button")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.view1Button)
        self.gridLayout_10.addWidget(self.view1Button, 0, 0, 1, 1)
        self.view2Button = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view2Button.setFont(font)
        self.view2Button.setObjectName("view2Button")
        self.buttonGroup.addButton(self.view2Button)
        self.gridLayout_10.addWidget(self.view2Button, 1, 0, 1, 1)
        self.view3Button = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view3Button.setFont(font)
        self.view3Button.setObjectName("view3Button")
        self.buttonGroup.addButton(self.view3Button)
        self.gridLayout_10.addWidget(self.view3Button, 2, 0, 1, 1)
        self.view4Button = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view4Button.setFont(font)
        self.view4Button.setObjectName("view4Button")
        self.buttonGroup.addButton(self.view4Button)
        self.gridLayout_10.addWidget(self.view4Button, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 1, 0, 1, 1)
        self.autoScalingCheck = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.autoScalingCheck.setFont(font)
        self.autoScalingCheck.setObjectName("autoScalingCheck")
        self.gridLayout_9.addWidget(self.autoScalingCheck, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.bgmax = QtWidgets.QLineEdit(self.groupBox)
        self.bgmax.setObjectName("bgmax")
        self.gridLayout_9.addWidget(self.bgmax, 2, 2, 1, 1)
        self.bgmin = QtWidgets.QLineEdit(self.groupBox)
        self.bgmin.setObjectName("bgmin")
        self.gridLayout_9.addWidget(self.bgmin, 2, 1, 1, 1)
        self.fgmin = QtWidgets.QLineEdit(self.groupBox)
        self.fgmin.setObjectName("fgmin")
        self.gridLayout_9.addWidget(self.fgmin, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 3, 0, 1, 1)
        self.fgmax = QtWidgets.QLineEdit(self.groupBox)
        self.fgmax.setObjectName("fgmax")
        self.gridLayout_9.addWidget(self.fgmax, 3, 2, 1, 1)
        self.usmax = QtWidgets.QLineEdit(self.groupBox)
        self.usmax.setObjectName("usmax")
        self.gridLayout_9.addWidget(self.usmax, 1, 2, 1, 1)
        self.usmin = QtWidgets.QLineEdit(self.groupBox)
        self.usmin.setObjectName("usmin")
        self.gridLayout_9.addWidget(self.usmin, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 2, 1, 1)
        self.bgwllabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bgwllabel.setFont(font)
        self.bgwllabel.setObjectName("bgwllabel")
        self.gridLayout_9.addWidget(self.bgwllabel, 4, 0, 1, 1)
        self.bgWavelength = QtWidgets.QComboBox(self.groupBox)
        self.bgWavelength.setEnabled(True)
        self.bgWavelength.setObjectName("bgWavelength")
        self.gridLayout_9.addWidget(self.bgWavelength, 4, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.viewSpectraList = QtWidgets.QListWidget(self.groupBox_4)
        self.viewSpectraList.setObjectName("viewSpectraList")
        self.gridLayout_6.addWidget(self.viewSpectraList, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.paletteType = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paletteType.setFont(font)
        self.paletteType.setObjectName("paletteType")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.gridLayout_3.addWidget(self.paletteType, 1, 2, 1, 1)
        self.transparentCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.transparentCheck.setFont(font)
        self.transparentCheck.setObjectName("transparentCheck")
        self.gridLayout_3.addWidget(self.transparentCheck, 0, 2, 1, 1)
        self.minBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minBox.setFont(font)
        self.minBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.minBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.minBox.setDecimals(3)
        self.minBox.setMinimum(-5000000.0)
        self.minBox.setMaximum(50000000.0)
        self.minBox.setObjectName("minBox")
        self.gridLayout_3.addWidget(self.minBox, 2, 2, 1, 1)
        self.minLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minLabel.setFont(font)
        self.minLabel.setObjectName("minLabel")
        self.gridLayout_3.addWidget(self.minLabel, 2, 0, 1, 2)
        self.maxLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxLabel.setFont(font)
        self.maxLabel.setObjectName("maxLabel")
        self.gridLayout_3.addWidget(self.maxLabel, 3, 0, 1, 2)
        self.maxBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxBox.setFont(font)
        self.maxBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.maxBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.maxBox.setPrefix("")
        self.maxBox.setDecimals(3)
        self.maxBox.setMinimum(-5000000.0)
        self.maxBox.setMaximum(500000.99)
        self.maxBox.setObjectName("maxBox")
        self.gridLayout_3.addWidget(self.maxBox, 3, 2, 1, 1)
        self.visibleCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visibleCheck.setFont(font)
        self.visibleCheck.setObjectName("visibleCheck")
        self.gridLayout_3.addWidget(self.visibleCheck, 0, 0, 1, 1)
        self.logarithmicScalingCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.logarithmicScalingCheck.setFont(font)
        self.logarithmicScalingCheck.setObjectName("logarithmicScalingCheck")
        self.gridLayout_3.addWidget(self.logarithmicScalingCheck, 4, 2, 1, 1)
        self.loadCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadCheck.setFont(font)
        self.loadCheck.setObjectName("loadCheck")
        self.gridLayout_3.addWidget(self.loadCheck, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 5, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.prefWLLabel.setBuddy(self.prefWLBox)
        self.WLLabel.setBuddy(self.WLList)
        self.label.setBuddy(self.userSoundBox)
        self.unselectedLabel.setBuddy(self.unselectedList)
        self.label_2.setBuddy(self.SFAFrameThreshBox)
        self.selectedLabel.setBuddy(self.selectedList)
        self.label_4.setBuddy(self.backgroundOxyBox)
        self.label_3.setBuddy(self.backgroundAbsorptionBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nameBox, self.PresetIDTextBox)
        MainWindow.setTabOrder(self.PresetIDTextBox, self.presetIDBox)
        MainWindow.setTabOrder(self.presetIDBox, self.detectorBox)
        MainWindow.setTabOrder(self.detectorBox, self.versionTextBox)
        MainWindow.setTabOrder(self.versionTextBox, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.saveAsButton)
        MainWindow.setTabOrder(self.saveAsButton, self.browseFactorySpectra)
        MainWindow.setTabOrder(self.browseFactorySpectra, self.FactorySpectraTextBox)
        MainWindow.setTabOrder(self.FactorySpectraTextBox, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.displayAllWLBox)
        MainWindow.setTabOrder(self.displayAllWLBox, self.WLList)
        MainWindow.setTabOrder(self.WLList, self.usvisibleBox)
        MainWindow.setTabOrder(self.usvisibleBox, self.prefWLBox)
        MainWindow.setTabOrder(self.prefWLBox, self.userSoundBox)
        MainWindow.setTabOrder(self.userSoundBox, self.unselectedList)
        MainWindow.setTabOrder(self.unselectedList, self.selectedList)
        MainWindow.setTabOrder(self.selectedList, self.addButton)
        MainWindow.setTabOrder(self.addButton, self.SFAFrameThreshBox)
        MainWindow.setTabOrder(self.SFAFrameThreshBox, self.backgroundAbsorptionBox)
        MainWindow.setTabOrder(self.backgroundAbsorptionBox, self.backgroundOxyBox)
        MainWindow.setTabOrder(self.backgroundOxyBox, self.deleteButton)
        MainWindow.setTabOrder(self.deleteButton, self.enableMultiPanel)
        MainWindow.setTabOrder(self.enableMultiPanel, self.view1Button)
        MainWindow.setTabOrder(self.view1Button, self.view2Button)
        MainWindow.setTabOrder(self.view2Button, self.view3Button)
        MainWindow.setTabOrder(self.view3Button, self.view4Button)
        MainWindow.setTabOrder(self.view4Button, self.autoScalingCheck)
        MainWindow.setTabOrder(self.autoScalingCheck, self.usmax)
        MainWindow.setTabOrder(self.usmax, self.bgmin)
        MainWindow.setTabOrder(self.bgmin, self.bgmax)
        MainWindow.setTabOrder(self.bgmax, self.fgmin)
        MainWindow.setTabOrder(self.fgmin, self.fgmax)
        MainWindow.setTabOrder(self.fgmax, self.usmin)
        MainWindow.setTabOrder(self.usmin, self.viewSpectraList)
        MainWindow.setTabOrder(self.viewSpectraList, self.paletteType)
        MainWindow.setTabOrder(self.paletteType, self.transparentCheck)
        MainWindow.setTabOrder(self.transparentCheck, self.minBox)
        MainWindow.setTabOrder(self.minBox, self.maxBox)
        MainWindow.setTabOrder(self.maxBox, self.visibleCheck)
        MainWindow.setTabOrder(self.visibleCheck, self.logarithmicScalingCheck)
        MainWindow.setTabOrder(self.logarithmicScalingCheck, self.loadCheck)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preset Editor"))
        self.groupBox_5.setTitle(_translate("MainWindow", "General"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.detektorLabel.setText(_translate("MainWindow", "Detector"))
        self.UniqueID.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.UniqueID.setText(_translate("MainWindow", "Unique ID"))
        self.PresetIDLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.PresetIDLabel.setText(_translate("MainWindow", "Preset ID"))
        self.versionLabel.setText(_translate("MainWindow", "Version"))
        self.PresestTypeLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.PresestTypeLabel.setText(_translate("MainWindow", "Preset Type"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.saveAsButton.setText(_translate("MainWindow", "Save As"))
        self.browseFactorySpectra.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse Factory Spectra</p></body></html>"))
        self.browseFactorySpectra.setText(_translate("MainWindow", "Factory Spectra"))
        self.displayAllWLBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display all Wavelengths</p></body></html>"))
        self.displayAllWLBox.setText(_translate("MainWindow", "Cycle Wavelengths"))
        self.prefWLLabel.setText(_translate("MainWindow", "Preferred Wavelength"))
        self.usvisibleBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ultrasound visible</p></body></html>"))
        self.usvisibleBox.setText(_translate("MainWindow", "Show Ultrasound"))
        self.WLList.setSortingEnabled(True)
        self.WLLabel.setText(_translate("MainWindow", "Wavelengths"))
        self.addWL.setText(_translate("MainWindow", "+"))
        self.removeWL.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Acquisition"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>User Sound Trim</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Speed of Sound"))
        self.deleteButton.setToolTip(_translate("MainWindow", "Remove Item"))
        self.deleteButton.setText(_translate("MainWindow", "<---"))
        self.selectedList.setSortingEnabled(True)
        self.unselectedLabel.setText(_translate("MainWindow", "Unselected"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>FRAMECORRTHRES</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "SFA Frame Threshold"))
        self.addButton.setToolTip(_translate("MainWindow", "Add Item"))
        self.addButton.setText(_translate("MainWindow", "--->"))
        self.selectedLabel.setText(_translate("MainWindow", "Selected"))
        self.label_4.setText(_translate("MainWindow", "Background Oxygenation"))
        self.label_3.setText(_translate("MainWindow", "Background Absorption"))
        self.unselectedList.setSortingEnabled(True)
        self.label_5.setText(_translate("MainWindow", "%"))
        self.label_12.setText(_translate("MainWindow", "Max Averaged Frames"))
        self.maxavgframes.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set to 1 to make SFA disapear.</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "SFA Buffer Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Processing"))
        self.enableMultiPanel.setText(_translate("MainWindow", "enable MultiPanel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "View Selection"))
        self.view1Button.setText(_translate("MainWindow", "Top Left"))
        self.view2Button.setText(_translate("MainWindow", "Top Right"))
        self.view3Button.setText(_translate("MainWindow", "Bottom Left"))
        self.view4Button.setText(_translate("MainWindow", "Bottom Right"))
        self.groupBox.setTitle(_translate("MainWindow", "View Settings"))
        self.label_8.setText(_translate("MainWindow", "min"))
        self.label_7.setText(_translate("MainWindow", "Ultrasound Scaling"))
        self.autoScalingCheck.setText(_translate("MainWindow", "Auto Scaling"))
        self.label_10.setText(_translate("MainWindow", "Background Scaling"))
        self.bgmax.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.bgmin.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.fgmin.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Foreground Scaling"))
        self.fgmax.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.usmax.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p><p><br/></p></body></html>"))
        self.usmin.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "max"))
        self.bgwllabel.setText(_translate("MainWindow", "Background Wavelength"))
        self.bgWavelength.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Panels"))
        self.viewSpectraList.setSortingEnabled(True)
        self.groupBox_2.setTitle(_translate("MainWindow", "Layer Settings"))
        self.label_6.setText(_translate("MainWindow", "Palette Type"))
        self.paletteType.setItemText(0, _translate("MainWindow", "DarkBlue"))
        self.paletteType.setItemText(1, _translate("MainWindow", "Bone"))
        self.paletteType.setItemText(2, _translate("MainWindow", "Contrast"))
        self.paletteType.setItemText(3, _translate("MainWindow", "Cyan"))
        self.paletteType.setItemText(4, _translate("MainWindow", "Gray"))
        self.paletteType.setItemText(5, _translate("MainWindow", "DarkGreen"))
        self.paletteType.setItemText(6, _translate("MainWindow", "Hot"))
        self.paletteType.setItemText(7, _translate("MainWindow", "Hue"))
        self.paletteType.setItemText(8, _translate("MainWindow", "Jet"))
        self.paletteType.setItemText(9, _translate("MainWindow", "LightBlue"))
        self.paletteType.setItemText(10, _translate("MainWindow", "LightGreen"))
        self.paletteType.setItemText(11, _translate("MainWindow", "LightRed"))
        self.paletteType.setItemText(12, _translate("MainWindow", "Magenta"))
        self.paletteType.setItemText(13, _translate("MainWindow", "DarkRed"))
        self.paletteType.setItemText(14, _translate("MainWindow", "RdBuBl"))
        self.paletteType.setItemText(15, _translate("MainWindow", "UnionJack"))
        self.paletteType.setItemText(16, _translate("MainWindow", "Yellow"))
        self.transparentCheck.setText(_translate("MainWindow", "Transparency"))
        self.minLabel.setText(_translate("MainWindow", "Lower Threshold"))
        self.maxLabel.setText(_translate("MainWindow", "Upper Threshold"))
        self.visibleCheck.setText(_translate("MainWindow", "Visible"))
        self.logarithmicScalingCheck.setText(_translate("MainWindow", "Logarithmic Scaling"))
        self.loadCheck.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Visualization"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

