# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preset_editor.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 838)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPlainTextEdit {\n"
"    font-family: \"Lucida Console\",\"Courier\";\n"
"    font-size: 9pt; \n"
"    background-color: #262626;\n"
"    selection-background-color: #2e5ea4;\n"
"/*    color: #dddddd;  */\n"
"}\n"
"QWidget:focus {\n"
"    border: 1px solid #2e5ea4;\n"
"}\n"
"\n"
"QListWidget:item:selected{\n"
"background: #2e5ea4\n"
"}\n"
"\n"
"QTapWidget{\n"
"    border: 1px solid #2e5ea4;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea4; \n"
"    border: 1px solid #2e5ea4;\n"
"    color: #ffffff;\n"
"}\n"
"/*QPushButton:flat {\n"
"    background-color: #666666;\n"
"    color: #ff0000;    \n"
"    border: 1px solid #cccccc;\n"
"}\n"
"QPushButton:default {\n"
"    background-color: #ff0000;\n"
"    color: #ff0000;    \n"
"    border: 1px solid #000000;\n"
"}*/\n"
"QPushButton {\n"
"    color: #cccccc;    \n"
"    border: 1px solid #888888;\n"
"    background: #ff0000;\n"
"    padding: 2px\n"
"} \n"
"QWidget {\n"
"    background: #222222;\n"
"    color: #cccccc;\n"
"}\n"
"\n"
"QTreeView::item:has-children {\n"
"    font-weight: bold;\n"
"}\n"
"QTreeView::item:selected {\n"
"     background-color: #2e5ea4;\n"
"     color: #cccccc;\n"
"     font-weight: bold;\n"
"}\n"
"\n"
"QTreeView::branch {\n"
"    background-color: #222222;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #222222;   \n"
"    border: 2px solid #cccccc;\n"
"    border-bottom-color: #cccccc; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #2e5ea4\n"
"    }\n"
"")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.loadButton.setObjectName("loadButton")
        self.saveAsButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveAsButton.setGeometry(QtCore.QRect(140, 20, 75, 23))
        self.saveAsButton.setAutoDefault(False)
        self.saveAsButton.setDefault(False)
        self.saveAsButton.setFlat(False)
        self.saveAsButton.setObjectName("saveAsButton")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(20, 80, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.detektorLabel = QtWidgets.QLabel(self.centralwidget)
        self.detektorLabel.setGeometry(QtCore.QRect(20, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.detektorLabel.setFont(font)
        self.detektorLabel.setObjectName("detektorLabel")
        self.nameBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.nameBox.setGeometry(QtCore.QRect(120, 70, 211, 41))
        self.nameBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.nameBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.nameBox.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.nameBox.setPlainText("")
        self.nameBox.setObjectName("nameBox")
        self.detectorBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.detectorBox.setGeometry(QtCore.QRect(120, 170, 211, 31))
        self.detectorBox.setPlainText("")
        self.detectorBox.setObjectName("detectorBox")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(40, 240, 541, 551))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.usvisibleBox = QtWidgets.QCheckBox(self.tab_3)
        self.usvisibleBox.setGeometry(QtCore.QRect(350, 100, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usvisibleBox.setFont(font)
        self.usvisibleBox.setObjectName("usvisibleBox")
        self.displayAllWLBox = QtWidgets.QCheckBox(self.tab_3)
        self.displayAllWLBox.setGeometry(QtCore.QRect(350, 60, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.displayAllWLBox.setFont(font)
        self.displayAllWLBox.setObjectName("displayAllWLBox")
        self.prefWLBox = QtWidgets.QComboBox(self.tab_3)
        self.prefWLBox.setGeometry(QtCore.QRect(360, 190, 91, 22))
        self.prefWLBox.setObjectName("prefWLBox")
        self.prefWLLabel = QtWidgets.QLabel(self.tab_3)
        self.prefWLLabel.setGeometry(QtCore.QRect(210, 190, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prefWLLabel.setFont(font)
        self.prefWLLabel.setObjectName("prefWLLabel")
        self.WLList = QtWidgets.QListWidget(self.tab_3)
        self.WLList.setGeometry(QtCore.QRect(50, 60, 121, 192))
        self.WLList.setObjectName("WLList")
        self.WLLabel = QtWidgets.QLabel(self.tab_3)
        self.WLLabel.setGeometry(QtCore.QRect(70, 30, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WLLabel.setFont(font)
        self.WLLabel.setObjectName("WLLabel")
        self.addWL = QtWidgets.QPushButton(self.tab_3)
        self.addWL.setGeometry(QtCore.QRect(30, 260, 75, 23))
        self.addWL.setObjectName("addWL")
        self.removeWL = QtWidgets.QPushButton(self.tab_3)
        self.removeWL.setGeometry(QtCore.QRect(120, 260, 75, 23))
        self.removeWL.setObjectName("removeWL")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.addButton = QtWidgets.QPushButton(self.tab)
        self.addButton.setGeometry(QtCore.QRect(230, 220, 51, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setToolTipDuration(-1)
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.tab)
        self.deleteButton.setGeometry(QtCore.QRect(230, 290, 51, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setToolTipDuration(-1)
        self.deleteButton.setObjectName("deleteButton")
        self.unselectedList = QtWidgets.QListWidget(self.tab)
        self.unselectedList.setGeometry(QtCore.QRect(50, 160, 131, 221))
        self.unselectedList.setObjectName("unselectedList")
        self.selectedList = QtWidgets.QListWidget(self.tab)
        self.selectedList.setGeometry(QtCore.QRect(330, 160, 141, 221))
        self.selectedList.setObjectName("selectedList")
        self.selectedLabel = QtWidgets.QLabel(self.tab)
        self.selectedLabel.setGeometry(QtCore.QRect(380, 130, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectedLabel.setFont(font)
        self.selectedLabel.setObjectName("selectedLabel")
        self.unselectedLabel = QtWidgets.QLabel(self.tab)
        self.unselectedLabel.setGeometry(QtCore.QRect(80, 130, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unselectedLabel.setFont(font)
        self.unselectedLabel.setObjectName("unselectedLabel")
        self.userSoundBox = QtWidgets.QSpinBox(self.tab)
        self.userSoundBox.setGeometry(QtCore.QRect(160, 20, 42, 22))
        self.userSoundBox.setMinimum(-150)
        self.userSoundBox.setMaximum(150)
        self.userSoundBox.setObjectName("userSoundBox")
        self.SFAFrameThreshBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.SFAFrameThreshBox.setGeometry(QtCore.QRect(390, 20, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SFAFrameThreshBox.setFont(font)
        self.SFAFrameThreshBox.setMaximum(1.0)
        self.SFAFrameThreshBox.setSingleStep(0.01)
        self.SFAFrameThreshBox.setObjectName("SFAFrameThreshBox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.backgroundAbsorptionBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.backgroundAbsorptionBox.setGeometry(QtCore.QRect(160, 70, 61, 22))
        self.backgroundAbsorptionBox.setDecimals(3)
        self.backgroundAbsorptionBox.setMaximum(0.1)
        self.backgroundAbsorptionBox.setSingleStep(0.001)
        self.backgroundAbsorptionBox.setObjectName("backgroundAbsorptionBox")
        self.backgroundOxyBox = QtWidgets.QSpinBox(self.tab)
        self.backgroundOxyBox.setGeometry(QtCore.QRect(390, 70, 42, 22))
        self.backgroundOxyBox.setMaximum(100)
        self.backgroundOxyBox.setObjectName("backgroundOxyBox")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(240, 70, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(440, 70, 47, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 60, 141, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.view1Button = QtWidgets.QRadioButton(self.groupBox_3)
        self.view1Button.setEnabled(True)
        self.view1Button.setGeometry(QtCore.QRect(10, 20, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view1Button.setFont(font)
        self.view1Button.setChecked(True)
        self.view1Button.setObjectName("view1Button")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.view1Button)
        self.view2Button = QtWidgets.QRadioButton(self.groupBox_3)
        self.view2Button.setGeometry(QtCore.QRect(10, 40, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view2Button.setFont(font)
        self.view2Button.setObjectName("view2Button")
        self.buttonGroup.addButton(self.view2Button)
        self.view3Button = QtWidgets.QRadioButton(self.groupBox_3)
        self.view3Button.setGeometry(QtCore.QRect(10, 60, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view3Button.setFont(font)
        self.view3Button.setObjectName("view3Button")
        self.buttonGroup.addButton(self.view3Button)
        self.view4Button = QtWidgets.QRadioButton(self.groupBox_3)
        self.view4Button.setGeometry(QtCore.QRect(10, 80, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view4Button.setFont(font)
        self.view4Button.setObjectName("view4Button")
        self.buttonGroup.addButton(self.view4Button)
        self.enableMultiPanel = QtWidgets.QCheckBox(self.tab_2)
        self.enableMultiPanel.setEnabled(True)
        self.enableMultiPanel.setGeometry(QtCore.QRect(20, 30, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enableMultiPanel.setFont(font)
        self.enableMultiPanel.setChecked(True)
        self.enableMultiPanel.setObjectName("enableMultiPanel")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(210, 10, 311, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.autoScalingCheck = QtWidgets.QCheckBox(self.groupBox)
        self.autoScalingCheck.setGeometry(QtCore.QRect(10, 30, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.autoScalingCheck.setFont(font)
        self.autoScalingCheck.setObjectName("autoScalingCheck")
        self.usmax = QtWidgets.QTextEdit(self.groupBox)
        self.usmax.setGeometry(QtCore.QRect(250, 60, 41, 21))
        self.usmax.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.usmax.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.usmax.setObjectName("usmax")
        self.usmin = QtWidgets.QTextEdit(self.groupBox)
        self.usmin.setGeometry(QtCore.QRect(170, 60, 41, 21))
        self.usmin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.usmin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.usmin.setObjectName("usmin")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(180, 30, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(260, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.bgmin = QtWidgets.QTextEdit(self.groupBox)
        self.bgmin.setGeometry(QtCore.QRect(170, 90, 41, 21))
        self.bgmin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bgmin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bgmin.setObjectName("bgmin")
        self.fgmin = QtWidgets.QTextEdit(self.groupBox)
        self.fgmin.setGeometry(QtCore.QRect(170, 120, 41, 21))
        self.fgmin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fgmin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fgmin.setObjectName("fgmin")
        self.bgmax = QtWidgets.QTextEdit(self.groupBox)
        self.bgmax.setGeometry(QtCore.QRect(250, 90, 41, 21))
        self.bgmax.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bgmax.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bgmax.setObjectName("bgmax")
        self.fgmax = QtWidgets.QTextEdit(self.groupBox)
        self.fgmax.setGeometry(QtCore.QRect(250, 120, 41, 21))
        self.fgmax.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fgmax.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fgmax.setObjectName("fgmax")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 200, 501, 301))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 30, 261, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.minBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.minBox.setGeometry(QtCore.QRect(170, 100, 61, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minBox.setFont(font)
        self.minBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.minBox.setDecimals(3)
        self.minBox.setMinimum(-5000000.0)
        self.minBox.setMaximum(50000000.0)
        self.minBox.setObjectName("minBox")
        self.maxBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.maxBox.setGeometry(QtCore.QRect(170, 140, 61, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxBox.setFont(font)
        self.maxBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.maxBox.setPrefix("")
        self.maxBox.setDecimals(3)
        self.maxBox.setMinimum(-5000000.0)
        self.maxBox.setMaximum(500000.99)
        self.maxBox.setObjectName("maxBox")
        self.minLabel = QtWidgets.QLabel(self.groupBox_2)
        self.minLabel.setGeometry(QtCore.QRect(20, 100, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minLabel.setFont(font)
        self.minLabel.setObjectName("minLabel")
        self.maxLabel = QtWidgets.QLabel(self.groupBox_2)
        self.maxLabel.setGeometry(QtCore.QRect(20, 140, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxLabel.setFont(font)
        self.maxLabel.setObjectName("maxLabel")
        self.paletteType = QtWidgets.QComboBox(self.groupBox_2)
        self.paletteType.setGeometry(QtCore.QRect(130, 60, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paletteType.setFont(font)
        self.paletteType.setObjectName("paletteType")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.paletteType.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.logarithmicScalingCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.logarithmicScalingCheck.setGeometry(QtCore.QRect(110, 180, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.logarithmicScalingCheck.setFont(font)
        self.logarithmicScalingCheck.setObjectName("logarithmicScalingCheck")
        self.loadCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.loadCheck.setGeometry(QtCore.QRect(20, 180, 70, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadCheck.setFont(font)
        self.loadCheck.setObjectName("loadCheck")
        self.visibleCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.visibleCheck.setGeometry(QtCore.QRect(20, 30, 70, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visibleCheck.setFont(font)
        self.visibleCheck.setObjectName("visibleCheck")
        self.transparentCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.transparentCheck.setGeometry(QtCore.QRect(140, 30, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.transparentCheck.setFont(font)
        self.transparentCheck.setObjectName("transparentCheck")
        self.viewSpectraList = QtWidgets.QListWidget(self.groupBox_4)
        self.viewSpectraList.setGeometry(QtCore.QRect(20, 40, 131, 211))
        self.viewSpectraList.setObjectName("viewSpectraList")
        self.tabWidget.addTab(self.tab_2, "")
        self.browseFactorySpectra = QtWidgets.QPushButton(self.centralwidget)
        self.browseFactorySpectra.setGeometry(QtCore.QRect(250, 20, 91, 23))
        self.browseFactorySpectra.setAutoDefault(False)
        self.browseFactorySpectra.setDefault(False)
        self.browseFactorySpectra.setFlat(False)
        self.browseFactorySpectra.setObjectName("browseFactorySpectra")
        self.FactorySpectraTextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.FactorySpectraTextBox.setGeometry(QtCore.QRect(370, 10, 201, 41))
        self.FactorySpectraTextBox.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.FactorySpectraTextBox.setReadOnly(True)
        self.FactorySpectraTextBox.setObjectName("FactorySpectraTextBox")
        self.PresetIDLabel = QtWidgets.QLabel(self.centralwidget)
        self.PresetIDLabel.setGeometry(QtCore.QRect(20, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PresetIDLabel.setFont(font)
        self.PresetIDLabel.setObjectName("PresetIDLabel")
        self.PresetIDTextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PresetIDTextBox.setGeometry(QtCore.QRect(440, 70, 141, 41))
        self.PresetIDTextBox.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.PresetIDTextBox.setReadOnly(True)
        self.PresetIDTextBox.setObjectName("PresetIDTextBox")
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(350, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        self.versionTextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.versionTextBox.setGeometry(QtCore.QRect(450, 170, 81, 31))
        self.versionTextBox.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.versionTextBox.setReadOnly(False)
        self.versionTextBox.setObjectName("versionTextBox")
        self.PresestTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.PresestTypeLabel.setGeometry(QtCore.QRect(350, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PresestTypeLabel.setFont(font)
        self.PresestTypeLabel.setObjectName("PresestTypeLabel")
        self.presetTypeBox = QtWidgets.QComboBox(self.centralwidget)
        self.presetTypeBox.setGeometry(QtCore.QRect(450, 130, 91, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.presetTypeBox.setFont(font)
        self.presetTypeBox.setObjectName("presetTypeBox")
        self.presetTypeBox.addItem("")
        self.presetTypeBox.addItem("")
        self.presetTypeBox.addItem("")
        self.UniqueID = QtWidgets.QLabel(self.centralwidget)
        self.UniqueID.setGeometry(QtCore.QRect(350, 80, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UniqueID.setFont(font)
        self.UniqueID.setObjectName("UniqueID")
        self.presetIDBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.presetIDBox.setGeometry(QtCore.QRect(120, 120, 211, 41))
        self.presetIDBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.presetIDBox.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.presetIDBox.setPlainText("")
        self.presetIDBox.setObjectName("presetIDBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preset Editor"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.saveAsButton.setText(_translate("MainWindow", "Save As"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.detektorLabel.setText(_translate("MainWindow", "Detector"))
        self.usvisibleBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ultrasound visible</p></body></html>"))
        self.usvisibleBox.setText(_translate("MainWindow", "Show Ultrasound"))
        self.displayAllWLBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display all Wavelengths</p></body></html>"))
        self.displayAllWLBox.setText(_translate("MainWindow", "Cycle Wavelengths"))
        self.prefWLLabel.setText(_translate("MainWindow", "Preferred Wavelength"))
        self.WLList.setSortingEnabled(True)
        self.WLLabel.setText(_translate("MainWindow", "Wavelengths"))
        self.addWL.setText(_translate("MainWindow", "+"))
        self.removeWL.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Acquisition"))
        self.addButton.setToolTip(_translate("MainWindow", "Add Item"))
        self.addButton.setText(_translate("MainWindow", "--->"))
        self.deleteButton.setToolTip(_translate("MainWindow", "Remove Item"))
        self.deleteButton.setText(_translate("MainWindow", "<---"))
        self.unselectedList.setSortingEnabled(True)
        self.selectedList.setSortingEnabled(True)
        self.selectedLabel.setText(_translate("MainWindow", "Selected"))
        self.unselectedLabel.setText(_translate("MainWindow", "Unselected"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>User Sound Trim</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Speed of Sound"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>FRAMECORRTHRES</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "SFA Frame Threshold"))
        self.label_3.setText(_translate("MainWindow", "Background Absorption"))
        self.label_4.setText(_translate("MainWindow", "Background Oxygenation"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Processing"))
        self.groupBox_3.setTitle(_translate("MainWindow", "View Selection"))
        self.view1Button.setText(_translate("MainWindow", "Top Left"))
        self.view2Button.setText(_translate("MainWindow", "Top Right"))
        self.view3Button.setText(_translate("MainWindow", "Bottom Left"))
        self.view4Button.setText(_translate("MainWindow", "Bottom Right"))
        self.enableMultiPanel.setText(_translate("MainWindow", "enable MultiPanel"))
        self.groupBox.setTitle(_translate("MainWindow", "View Settings"))
        self.autoScalingCheck.setText(_translate("MainWindow", "Auto Scaling"))
        self.usmax.setToolTip(_translate("MainWindow", "<html><head/><body><p>-1 = Minimum of Image</p><p>1 = Maximum of Image</p><p>0 = Scale from Zero</p><p>decimal value = Histogram Threshold</p></body></html>"))
        self.usmin.setToolTip(_translate("MainWindow", "<html><head/><body><p>-1 = Minimum of Image</p><p>1 = Maximum of Image</p><p>0 = Scale from Zero</p><p>decimal value = Histogram Threshold</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Ultrasound Scaling"))
        self.label_8.setText(_translate("MainWindow", "min"))
        self.label_9.setText(_translate("MainWindow", "max"))
        self.bgmin.setToolTip(_translate("MainWindow", "<html><head/><body><p>-1 = Minimum of Image</p><p>1 = Maximum of Image</p><p>0 = Scale from Zero</p><p>decimal value = Histogram Threshold</p></body></html>"))
        self.fgmin.setToolTip(_translate("MainWindow", "<html><head/><body><p>-1 = Minimum of Image</p><p>1 = Maximum of Image</p><p>0 = Scale from Zero</p><p>decimal value = Histogram Threshold</p></body></html>"))
        self.bgmax.setToolTip(_translate("MainWindow", "<html><head/><body><p>-1 = Minimum of Image</p><p>1 = Maximum of Image</p><p>0 = Scale from Zero</p><p>decimal value = Histogram Threshold</p></body></html>"))
        self.fgmax.setToolTip(_translate("MainWindow", "<html><head/><body><p>-1 = Minimum of Image</p><p>1 = Maximum of Image</p><p>0 = Scale from Zero</p><p>decimal value = Histogram Threshold</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Background Scaling"))
        self.label_11.setText(_translate("MainWindow", "Foreground Scaling"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Panels"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Layer Settings"))
        self.minLabel.setText(_translate("MainWindow", "Lower Threshold"))
        self.maxLabel.setText(_translate("MainWindow", "Upper Threshold"))
        self.paletteType.setItemText(0, _translate("MainWindow", "DarkBlue"))
        self.paletteType.setItemText(1, _translate("MainWindow", "Bone"))
        self.paletteType.setItemText(2, _translate("MainWindow", "Contrast"))
        self.paletteType.setItemText(3, _translate("MainWindow", "Cyan"))
        self.paletteType.setItemText(4, _translate("MainWindow", "Gray"))
        self.paletteType.setItemText(5, _translate("MainWindow", "DarkGreen"))
        self.paletteType.setItemText(6, _translate("MainWindow", "Hot"))
        self.paletteType.setItemText(7, _translate("MainWindow", "Hue"))
        self.paletteType.setItemText(8, _translate("MainWindow", "Jet"))
        self.paletteType.setItemText(9, _translate("MainWindow", "LightBlue"))
        self.paletteType.setItemText(10, _translate("MainWindow", "LightGreen"))
        self.paletteType.setItemText(11, _translate("MainWindow", "LightRed"))
        self.paletteType.setItemText(12, _translate("MainWindow", "Magenta"))
        self.paletteType.setItemText(13, _translate("MainWindow", "DarkRed"))
        self.paletteType.setItemText(14, _translate("MainWindow", "RdBuBl"))
        self.paletteType.setItemText(15, _translate("MainWindow", "UnionJack"))
        self.paletteType.setItemText(16, _translate("MainWindow", "Yellow"))
        self.label_6.setText(_translate("MainWindow", "Palette Type"))
        self.logarithmicScalingCheck.setText(_translate("MainWindow", "Logarithmic Scaling"))
        self.loadCheck.setText(_translate("MainWindow", "Load"))
        self.visibleCheck.setText(_translate("MainWindow", "Visible"))
        self.transparentCheck.setText(_translate("MainWindow", "Transparency"))
        self.viewSpectraList.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Visualization"))
        self.browseFactorySpectra.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse Factory Spectra</p></body></html>"))
        self.browseFactorySpectra.setText(_translate("MainWindow", "Factory Spectra"))
        self.PresetIDLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.PresetIDLabel.setText(_translate("MainWindow", "Preset ID"))
        self.versionLabel.setText(_translate("MainWindow", "Version"))
        self.PresestTypeLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.PresestTypeLabel.setText(_translate("MainWindow", "Preset Type"))
        self.presetTypeBox.setItemText(0, _translate("MainWindow", "Factory"))
        self.presetTypeBox.setItemText(1, _translate("MainWindow", "Customer"))
        self.presetTypeBox.setItemText(2, _translate("MainWindow", "User"))
        self.UniqueID.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.UniqueID.setText(_translate("MainWindow", "Unique ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

