# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source\resources\preset_editor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 915)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPlainTextEdit {\n"
"    font-family: \"Lucida Console\",\"Courier\";\n"
"    font-size: 9pt; \n"
"    background-color: #262626;\n"
"    selection-background-color: #2e5ea4;\n"
"/*    color: #dddddd;  */\n"
"}\n"
"QWidget:focus {\n"
"    border: 1px solid #2e5ea4;\n"
"}\n"
"\n"
"QListWidget:item:selected{\n"
"background: #2e5ea4\n"
"}\n"
"\n"
"QTapWidget{\n"
"    border: 1px solid #2e5ea4;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2e5ea4; \n"
"    border: 1px solid #2e5ea4;\n"
"    color: #ffffff;\n"
"}\n"
"/*QPushButton:flat {\n"
"    background-color: #666666;\n"
"    color: #ff0000;    \n"
"    border: 1px solid #cccccc;\n"
"}\n"
"QPushButton:default {\n"
"    background-color: #ff0000;\n"
"    color: #ff0000;    \n"
"    border: 1px solid #000000;\n"
"}*/\n"
"QPushButton {\n"
"    color: #cccccc;    \n"
"    border: 1px solid #888888;\n"
"    background: #ff0000;\n"
"    padding: 2px\n"
"} \n"
"QWidget {\n"
"    background: #222222;\n"
"    color: #cccccc;\n"
"}\n"
"\n"
"QTreeView::item:has-children {\n"
"    font-weight: bold;\n"
"}\n"
"QTreeView::item:selected {\n"
"     background-color: #2e5ea4;\n"
"     color: #cccccc;\n"
"     font-weight: bold;\n"
"}\n"
"\n"
"QTreeView::branch {\n"
"    background-color: #222222;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #222222;   \n"
"    border: 2px solid #cccccc;\n"
"    border-bottom-color: #cccccc; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #2e5ea4\n"
"    }\n"
"")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.compatibilityBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compatibilityBox.sizePolicy().hasHeightForWidth())
        self.compatibilityBox.setSizePolicy(sizePolicy)
        self.compatibilityBox.setMinimumSize(QtCore.QSize(0, 70))
        self.compatibilityBox.setAutoFillBackground(False)
        self.compatibilityBox.setStyleSheet("color:#2ea42e")
        self.compatibilityBox.setObjectName("compatibilityBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.compatibilityBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PresetCompatLabel = QtWidgets.QLabel(self.compatibilityBox)
        self.PresetCompatLabel.setObjectName("PresetCompatLabel")
        self.gridLayout_5.addWidget(self.PresetCompatLabel, 0, 1, 1, 1)
        self.PECompatLabel = QtWidgets.QLabel(self.compatibilityBox)
        self.PECompatLabel.setObjectName("PECompatLabel")
        self.gridLayout_5.addWidget(self.PECompatLabel, 0, 0, 1, 1)
        self.CompatMsg = QtWidgets.QLabel(self.compatibilityBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.CompatMsg.setFont(font)
        self.CompatMsg.setAutoFillBackground(False)
        self.CompatMsg.setStyleSheet("")
        self.CompatMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CompatMsg.setObjectName("CompatMsg")
        self.gridLayout_5.addWidget(self.CompatMsg, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.compatibilityBox, 4, 0, 1, 4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.contentHashBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.contentHashBox.setEnabled(False)
        self.contentHashBox.setStyleSheet("color : rgb(120, 120, 120)")
        self.contentHashBox.setText("")
        self.contentHashBox.setObjectName("contentHashBox")
        self.gridLayout_2.addWidget(self.contentHashBox, 6, 3, 1, 1)
        self.contentHashLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentHashLabel.sizePolicy().hasHeightForWidth())
        self.contentHashLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contentHashLabel.setFont(font)
        self.contentHashLabel.setToolTipDuration(-2)
        self.contentHashLabel.setObjectName("contentHashLabel")
        self.gridLayout_2.addWidget(self.contentHashLabel, 6, 2, 1, 1)
        self.detektorLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detektorLabel.sizePolicy().hasHeightForWidth())
        self.detektorLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.detektorLabel.setFont(font)
        self.detektorLabel.setObjectName("detektorLabel")
        self.gridLayout_2.addWidget(self.detektorLabel, 6, 0, 1, 1)
        self.presetIDBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.presetIDBox.setEnabled(False)
        self.presetIDBox.setObjectName("presetIDBox")
        self.gridLayout_2.addWidget(self.presetIDBox, 1, 1, 1, 3)
        self.versionTextBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.versionTextBox.setObjectName("versionTextBox")
        self.gridLayout_2.addWidget(self.versionTextBox, 5, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 2, 1, 1)
        self.appscientistname = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appscientistname.sizePolicy().hasHeightForWidth())
        self.appscientistname.setSizePolicy(sizePolicy)
        self.appscientistname.setMaxLength(3)
        self.appscientistname.setObjectName("appscientistname")
        self.gridLayout_2.addWidget(self.appscientistname, 3, 3, 1, 1)
        self.PresestTypeLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PresestTypeLabel.sizePolicy().hasHeightForWidth())
        self.PresestTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PresestTypeLabel.setFont(font)
        self.PresestTypeLabel.setObjectName("PresestTypeLabel")
        self.gridLayout_2.addWidget(self.PresestTypeLabel, 5, 2, 1, 1)
        self.PresetIDLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PresetIDLabel.sizePolicy().hasHeightForWidth())
        self.PresetIDLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PresetIDLabel.setFont(font)
        self.PresetIDLabel.setObjectName("PresetIDLabel")
        self.gridLayout_2.addWidget(self.PresetIDLabel, 1, 0, 1, 1)
        self.detectorBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.detectorBox.setObjectName("detectorBox")
        self.gridLayout_2.addWidget(self.detectorBox, 6, 1, 1, 1)
        self.nameBox = QtWidgets.QLineEdit(self.groupBox_5)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout_2.addWidget(self.nameBox, 3, 1, 1, 1)
        self.PresetType = QtWidgets.QLineEdit(self.groupBox_5)
        self.PresetType.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PresetType.setFont(font)
        self.PresetType.setObjectName("PresetType")
        self.gridLayout_2.addWidget(self.PresetType, 4, 3, 2, 1)
        self.versionLabel = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLabel.sizePolicy().hasHeightForWidth())
        self.versionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_2.addWidget(self.versionLabel, 5, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 10, 0, 2, 4)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_4.addWidget(self.loadButton, 2, 0, 1, 1)
        self.saveAsButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveAsButton.setAutoDefault(False)
        self.saveAsButton.setDefault(False)
        self.saveAsButton.setFlat(False)
        self.saveAsButton.setObjectName("saveAsButton")
        self.gridLayout_4.addWidget(self.saveAsButton, 2, 3, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.FactorySpectraTextBox = QtWidgets.QLineEdit(self.groupBox_6)
        self.FactorySpectraTextBox.setEnabled(False)
        self.FactorySpectraTextBox.setObjectName("FactorySpectraTextBox")
        self.horizontalLayout.addWidget(self.FactorySpectraTextBox)
        self.browseFactorySpectra = QtWidgets.QPushButton(self.groupBox_6)
        self.browseFactorySpectra.setAutoDefault(False)
        self.browseFactorySpectra.setDefault(False)
        self.browseFactorySpectra.setFlat(False)
        self.browseFactorySpectra.setObjectName("browseFactorySpectra")
        self.horizontalLayout.addWidget(self.browseFactorySpectra)
        self.gridLayout_4.addWidget(self.groupBox_6, 3, 0, 1, 4)
        self.importScanButton = QtWidgets.QPushButton(self.centralwidget)
        self.importScanButton.setObjectName("importScanButton")
        self.gridLayout_4.addWidget(self.importScanButton, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.prefWLLabel = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prefWLLabel.sizePolicy().hasHeightForWidth())
        self.prefWLLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prefWLLabel.setFont(font)
        self.prefWLLabel.setObjectName("prefWLLabel")
        self.gridLayout.addWidget(self.prefWLLabel, 1, 3, 1, 1)
        self.WLList = QtWidgets.QListWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WLList.sizePolicy().hasHeightForWidth())
        self.WLList.setSizePolicy(sizePolicy)
        self.WLList.setObjectName("WLList")
        self.gridLayout.addWidget(self.WLList, 1, 0, 5, 2)
        self.displayAllWLBox = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.displayAllWLBox.setFont(font)
        self.displayAllWLBox.setObjectName("displayAllWLBox")
        self.gridLayout.addWidget(self.displayAllWLBox, 4, 3, 1, 1)
        self.WLLabel = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WLLabel.sizePolicy().hasHeightForWidth())
        self.WLLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WLLabel.setFont(font)
        self.WLLabel.setObjectName("WLLabel")
        self.gridLayout.addWidget(self.WLLabel, 0, 0, 1, 1)
        self.usvisibleBox = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usvisibleBox.setFont(font)
        self.usvisibleBox.setObjectName("usvisibleBox")
        self.gridLayout.addWidget(self.usvisibleBox, 3, 3, 1, 1)
        self.prefWLBox = QtWidgets.QComboBox(self.tab_3)
        self.prefWLBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.prefWLBox.setObjectName("prefWLBox")
        self.gridLayout.addWidget(self.prefWLBox, 2, 3, 1, 1)
        self.addWL = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addWL.sizePolicy().hasHeightForWidth())
        self.addWL.setSizePolicy(sizePolicy)
        self.addWL.setObjectName("addWL")
        self.gridLayout.addWidget(self.addWL, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 2, 1, 1)
        self.removeWL = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeWL.sizePolicy().hasHeightForWidth())
        self.removeWL.setSizePolicy(sizePolicy)
        self.removeWL.setObjectName("removeWL")
        self.gridLayout.addWidget(self.removeWL, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 0, 3, 1, 1)
        self.SFAFrameThreshBox = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SFAFrameThreshBox.setFont(font)
        self.SFAFrameThreshBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SFAFrameThreshBox.setMaximum(1.0)
        self.SFAFrameThreshBox.setSingleStep(0.01)
        self.SFAFrameThreshBox.setObjectName("SFAFrameThreshBox")
        self.gridLayout_13.addWidget(self.SFAFrameThreshBox, 0, 4, 1, 1)
        self.maxavgframes = QtWidgets.QSpinBox(self.groupBox_9)
        self.maxavgframes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.maxavgframes.setMinimum(1)
        self.maxavgframes.setMaximum(99)
        self.maxavgframes.setProperty("value", 7)
        self.maxavgframes.setObjectName("maxavgframes")
        self.gridLayout_13.addWidget(self.maxavgframes, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 0, 0, 1, 1)
        self.sfabuffersize = QtWidgets.QSpinBox(self.groupBox_9)
        self.sfabuffersize.setMinimum(1)
        self.sfabuffersize.setObjectName("sfabuffersize")
        self.gridLayout_13.addWidget(self.sfabuffersize, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_9, 2, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 7, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 270))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.unselectedLabel = QtWidgets.QLabel(self.groupBox_10)
        self.unselectedLabel.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unselectedLabel.setFont(font)
        self.unselectedLabel.setObjectName("unselectedLabel")
        self.gridLayout_14.addWidget(self.unselectedLabel, 0, 0, 1, 1)
        self.selectedLabel = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectedLabel.setFont(font)
        self.selectedLabel.setObjectName("selectedLabel")
        self.gridLayout_14.addWidget(self.selectedLabel, 0, 2, 1, 1)
        self.unselectedList = QtWidgets.QListWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unselectedList.sizePolicy().hasHeightForWidth())
        self.unselectedList.setSizePolicy(sizePolicy)
        self.unselectedList.setMinimumSize(QtCore.QSize(100, 200))
        self.unselectedList.setObjectName("unselectedList")
        self.gridLayout_14.addWidget(self.unselectedList, 1, 0, 2, 1)
        self.addButton = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setToolTipDuration(-1)
        self.addButton.setObjectName("addButton")
        self.gridLayout_14.addWidget(self.addButton, 1, 1, 1, 1)
        self.selectedList = QtWidgets.QListWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedList.sizePolicy().hasHeightForWidth())
        self.selectedList.setSizePolicy(sizePolicy)
        self.selectedList.setMinimumSize(QtCore.QSize(0, 200))
        self.selectedList.setObjectName("selectedList")
        self.gridLayout_14.addWidget(self.selectedList, 1, 2, 2, 1)
        self.deleteButton = QtWidgets.QPushButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setToolTipDuration(-1)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_14.addWidget(self.deleteButton, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 4, 0, 1, 3)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.userSoundBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.userSoundBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.userSoundBox.setMinimum(-150)
        self.userSoundBox.setMaximum(150)
        self.userSoundBox.setObjectName("userSoundBox")
        self.gridLayout_7.addWidget(self.userSoundBox, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 1, 1)
        self.filterTypeBox = QtWidgets.QComboBox(self.groupBox_7)
        self.filterTypeBox.setObjectName("filterTypeBox")
        self.gridLayout_7.addWidget(self.filterTypeBox, 1, 1, 1, 1)
        self.invertReconstruction = QtWidgets.QCheckBox(self.groupBox_7)
        self.invertReconstruction.setObjectName("invertReconstruction")
        self.gridLayout_7.addWidget(self.invertReconstruction, 1, 3, 1, 2)
        self.backprojectionDerivative = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backprojectionDerivative.sizePolicy().hasHeightForWidth())
        self.backprojectionDerivative.setSizePolicy(sizePolicy)
        self.backprojectionDerivative.setObjectName("backprojectionDerivative")
        self.gridLayout_7.addWidget(self.backprojectionDerivative, 0, 5, 1, 1)
        self.backprojectionAuto = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backprojectionAuto.sizePolicy().hasHeightForWidth())
        self.backprojectionAuto.setSizePolicy(sizePolicy)
        self.backprojectionAuto.setChecked(True)
        self.backprojectionAuto.setObjectName("backprojectionAuto")
        self.gridLayout_7.addWidget(self.backprojectionAuto, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setMinimumSize(QtCore.QSize(80, 0))
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 3, 1, 1)
        self.backprojectionDirect = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backprojectionDirect.sizePolicy().hasHeightForWidth())
        self.backprojectionDirect.setSizePolicy(sizePolicy)
        self.backprojectionDirect.setObjectName("backprojectionDirect")
        self.gridLayout_7.addWidget(self.backprojectionDirect, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 1, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_7, 0, 0, 1, 3)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.backgroundAbsorptionBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.backgroundAbsorptionBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.backgroundAbsorptionBox.setDecimals(3)
        self.backgroundAbsorptionBox.setMaximum(0.1)
        self.backgroundAbsorptionBox.setSingleStep(0.001)
        self.backgroundAbsorptionBox.setObjectName("backgroundAbsorptionBox")
        self.gridLayout_12.addWidget(self.backgroundAbsorptionBox, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 0, 2, 1, 1)
        self.backgroundOxyBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.backgroundOxyBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.backgroundOxyBox.setMaximum(100)
        self.backgroundOxyBox.setObjectName("backgroundOxyBox")
        self.gridLayout_12.addWidget(self.backgroundOxyBox, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_8, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.view1Button = QtWidgets.QRadioButton(self.groupBox_3)
        self.view1Button.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view1Button.setFont(font)
        self.view1Button.setChecked(True)
        self.view1Button.setObjectName("view1Button")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.view1Button)
        self.gridLayout_10.addWidget(self.view1Button, 1, 0, 1, 1)
        self.view3Button = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view3Button.setFont(font)
        self.view3Button.setObjectName("view3Button")
        self.buttonGroup.addButton(self.view3Button)
        self.gridLayout_10.addWidget(self.view3Button, 3, 0, 1, 1)
        self.view2Button = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view2Button.setFont(font)
        self.view2Button.setObjectName("view2Button")
        self.buttonGroup.addButton(self.view2Button)
        self.gridLayout_10.addWidget(self.view2Button, 2, 0, 1, 1)
        self.view4Button = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view4Button.setFont(font)
        self.view4Button.setObjectName("view4Button")
        self.buttonGroup.addButton(self.view4Button)
        self.gridLayout_10.addWidget(self.view4Button, 4, 0, 1, 1)
        self.enableMultiPanel = QtWidgets.QCheckBox(self.groupBox_3)
        self.enableMultiPanel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enableMultiPanel.setFont(font)
        self.enableMultiPanel.setChecked(True)
        self.enableMultiPanel.setObjectName("enableMultiPanel")
        self.gridLayout_10.addWidget(self.enableMultiPanel, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 1, 0, 1, 1)
        self.autoScalingCheck = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.autoScalingCheck.setFont(font)
        self.autoScalingCheck.setObjectName("autoScalingCheck")
        self.gridLayout_9.addWidget(self.autoScalingCheck, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.bgmax = QtWidgets.QLineEdit(self.groupBox)
        self.bgmax.setObjectName("bgmax")
        self.gridLayout_9.addWidget(self.bgmax, 2, 2, 1, 1)
        self.bgmin = QtWidgets.QLineEdit(self.groupBox)
        self.bgmin.setObjectName("bgmin")
        self.gridLayout_9.addWidget(self.bgmin, 2, 1, 1, 1)
        self.fgmin = QtWidgets.QLineEdit(self.groupBox)
        self.fgmin.setObjectName("fgmin")
        self.gridLayout_9.addWidget(self.fgmin, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 3, 0, 1, 1)
        self.fgmax = QtWidgets.QLineEdit(self.groupBox)
        self.fgmax.setObjectName("fgmax")
        self.gridLayout_9.addWidget(self.fgmax, 3, 2, 1, 1)
        self.usmax = QtWidgets.QLineEdit(self.groupBox)
        self.usmax.setObjectName("usmax")
        self.gridLayout_9.addWidget(self.usmax, 1, 2, 1, 1)
        self.usmin = QtWidgets.QLineEdit(self.groupBox)
        self.usmin.setObjectName("usmin")
        self.gridLayout_9.addWidget(self.usmin, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 2, 1, 1)
        self.bgwllabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bgwllabel.setFont(font)
        self.bgwllabel.setObjectName("bgwllabel")
        self.gridLayout_9.addWidget(self.bgwllabel, 4, 0, 1, 1)
        self.bgWavelength = QtWidgets.QComboBox(self.groupBox)
        self.bgWavelength.setEnabled(True)
        self.bgWavelength.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.bgWavelength.setObjectName("bgWavelength")
        self.gridLayout_9.addWidget(self.bgWavelength, 4, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.viewSpectraList = QtWidgets.QListWidget(self.groupBox_4)
        self.viewSpectraList.setObjectName("viewSpectraList")
        self.gridLayout_6.addWidget(self.viewSpectraList, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.paletteType = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paletteType.setFont(font)
        self.paletteType.setObjectName("paletteType")
        self.gridLayout_3.addWidget(self.paletteType, 1, 2, 1, 1)
        self.transparentCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.transparentCheck.setFont(font)
        self.transparentCheck.setObjectName("transparentCheck")
        self.gridLayout_3.addWidget(self.transparentCheck, 0, 2, 1, 1)
        self.minBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minBox.setFont(font)
        self.minBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.minBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.minBox.setDecimals(3)
        self.minBox.setMinimum(-5000000.0)
        self.minBox.setMaximum(50000000.0)
        self.minBox.setObjectName("minBox")
        self.gridLayout_3.addWidget(self.minBox, 2, 2, 1, 1)
        self.minLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minLabel.setFont(font)
        self.minLabel.setObjectName("minLabel")
        self.gridLayout_3.addWidget(self.minLabel, 2, 0, 1, 2)
        self.maxLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxLabel.setFont(font)
        self.maxLabel.setObjectName("maxLabel")
        self.gridLayout_3.addWidget(self.maxLabel, 3, 0, 1, 2)
        self.maxBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxBox.setFont(font)
        self.maxBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.maxBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.maxBox.setPrefix("")
        self.maxBox.setDecimals(3)
        self.maxBox.setMinimum(-5000000.0)
        self.maxBox.setMaximum(500000.99)
        self.maxBox.setProperty("value", 0.5)
        self.maxBox.setObjectName("maxBox")
        self.gridLayout_3.addWidget(self.maxBox, 3, 2, 1, 1)
        self.visibleCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visibleCheck.setFont(font)
        self.visibleCheck.setObjectName("visibleCheck")
        self.gridLayout_3.addWidget(self.visibleCheck, 0, 0, 1, 1)
        self.logarithmicScalingCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.logarithmicScalingCheck.setFont(font)
        self.logarithmicScalingCheck.setObjectName("logarithmicScalingCheck")
        self.gridLayout_3.addWidget(self.logarithmicScalingCheck, 4, 2, 1, 1)
        self.loadCheck = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadCheck.setFont(font)
        self.loadCheck.setObjectName("loadCheck")
        self.gridLayout_3.addWidget(self.loadCheck, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.mainPanelPaletteType = QtWidgets.QComboBox(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mainPanelPaletteType.setFont(font)
        self.mainPanelPaletteType.setObjectName("mainPanelPaletteType")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.mainPanelPaletteType.addItem("")
        self.gridLayout_15.addWidget(self.mainPanelPaletteType, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 1, 0, 1, 1)
        self.mainPanelBrightnessDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.mainPanelBrightnessDoubleSpinBox.setObjectName("mainPanelBrightnessDoubleSpinBox")
        self.gridLayout_15.addWidget(self.mainPanelBrightnessDoubleSpinBox, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 0, 0, 1, 1)
        self.mainPanelContrastDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.mainPanelContrastDoubleSpinBox.setObjectName("mainPanelContrastDoubleSpinBox")
        self.gridLayout_15.addWidget(self.mainPanelContrastDoubleSpinBox, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_15.addWidget(self.label_19, 1, 2, 1, 1)
        self.mainPanelOPUSBrightnessDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.mainPanelOPUSBrightnessDoubleSpinBox.setObjectName("mainPanelOPUSBrightnessDoubleSpinBox")
        self.gridLayout_15.addWidget(self.mainPanelOPUSBrightnessDoubleSpinBox, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 2, 2, 1, 1)
        self.mainPanelOPUSContrastDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.mainPanelOPUSContrastDoubleSpinBox.setObjectName("mainPanelOPUSContrastDoubleSpinBox")
        self.gridLayout_15.addWidget(self.mainPanelOPUSContrastDoubleSpinBox, 2, 3, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabRestrictions = QtWidgets.QWidget()
        self.tabRestrictions.setObjectName("tabRestrictions")
        self.tabWidget.addTab(self.tabRestrictions, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBodyRegion = QtWidgets.QGroupBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBodyRegion.sizePolicy().hasHeightForWidth())
        self.groupBodyRegion.setSizePolicy(sizePolicy)
        self.groupBodyRegion.setObjectName("groupBodyRegion")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBodyRegion)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_23 = QtWidgets.QLabel(self.groupBodyRegion)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.scanLocations = QtWidgets.QPlainTextEdit(self.groupBodyRegion)
        self.scanLocations.setObjectName("scanLocations")
        self.verticalLayout.addWidget(self.scanLocations)
        self.gridLayout_16.addWidget(self.groupBodyRegion, 0, 1, 1, 1)
        self.groupBodyAtlas = QtWidgets.QGroupBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBodyAtlas.sizePolicy().hasHeightForWidth())
        self.groupBodyAtlas.setSizePolicy(sizePolicy)
        self.groupBodyAtlas.setObjectName("groupBodyAtlas")
        self.gridLayout_16.addWidget(self.groupBodyAtlas, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_4.addWidget(self.tabWidget, 12, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.prefWLLabel.setBuddy(self.prefWLBox)
        self.WLLabel.setBuddy(self.WLList)
        self.label_2.setBuddy(self.SFAFrameThreshBox)
        self.unselectedLabel.setBuddy(self.unselectedList)
        self.selectedLabel.setBuddy(self.selectedList)
        self.label.setBuddy(self.userSoundBox)
        self.label_4.setBuddy(self.backgroundOxyBox)
        self.label_3.setBuddy(self.backgroundAbsorptionBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.detectorBox, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.displayAllWLBox)
        MainWindow.setTabOrder(self.displayAllWLBox, self.WLList)
        MainWindow.setTabOrder(self.WLList, self.usvisibleBox)
        MainWindow.setTabOrder(self.usvisibleBox, self.prefWLBox)
        MainWindow.setTabOrder(self.prefWLBox, self.view1Button)
        MainWindow.setTabOrder(self.view1Button, self.view2Button)
        MainWindow.setTabOrder(self.view2Button, self.view3Button)
        MainWindow.setTabOrder(self.view3Button, self.view4Button)
        MainWindow.setTabOrder(self.view4Button, self.autoScalingCheck)
        MainWindow.setTabOrder(self.autoScalingCheck, self.usmax)
        MainWindow.setTabOrder(self.usmax, self.bgmin)
        MainWindow.setTabOrder(self.bgmin, self.bgmax)
        MainWindow.setTabOrder(self.bgmax, self.fgmin)
        MainWindow.setTabOrder(self.fgmin, self.fgmax)
        MainWindow.setTabOrder(self.fgmax, self.usmin)
        MainWindow.setTabOrder(self.usmin, self.viewSpectraList)
        MainWindow.setTabOrder(self.viewSpectraList, self.paletteType)
        MainWindow.setTabOrder(self.paletteType, self.transparentCheck)
        MainWindow.setTabOrder(self.transparentCheck, self.minBox)
        MainWindow.setTabOrder(self.minBox, self.maxBox)
        MainWindow.setTabOrder(self.maxBox, self.visibleCheck)
        MainWindow.setTabOrder(self.visibleCheck, self.logarithmicScalingCheck)
        MainWindow.setTabOrder(self.logarithmicScalingCheck, self.loadCheck)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preset Editor"))
        self.compatibilityBox.setTitle(_translate("MainWindow", "Compatibility"))
        self.PresetCompatLabel.setText(_translate("MainWindow", "<Preset Compat Version>"))
        self.PECompatLabel.setText(_translate("MainWindow", "<PE Compat Version>"))
        self.CompatMsg.setText(_translate("MainWindow", "<Compat Message>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "General"))
        self.contentHashLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Unique Content Hash<br>(excludes Preset ID, Name, Version and AppScientist)</p></body></html>"))
        self.contentHashLabel.setText(_translate("MainWindow", "Content Hash"))
        self.detektorLabel.setText(_translate("MainWindow", "Detector"))
        self.nameLabel.setText(_translate("MainWindow", "Name in ViewMSOTc"))
        self.label_14.setText(_translate("MainWindow", "App Scientist"))
        self.appscientistname.setToolTip(_translate("MainWindow", "<html><head/><body><p>Initials (max 3 characters)</p></body></html>"))
        self.PresestTypeLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.PresestTypeLabel.setText(_translate("MainWindow", "Preset Type"))
        self.PresetIDLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Preset Identifier</p></body></html>"))
        self.PresetIDLabel.setText(_translate("MainWindow", "Preset ID"))
        self.versionLabel.setText(_translate("MainWindow", "Version"))
        self.loadButton.setText(_translate("MainWindow", "Load Preset"))
        self.saveAsButton.setText(_translate("MainWindow", "Save As"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Factory Spectra"))
        self.label_15.setText(_translate("MainWindow", "Source Folder:"))
        self.browseFactorySpectra.setToolTip(_translate("MainWindow", "<html><head/><body><p>Browse Factory Spectra</p></body></html>"))
        self.browseFactorySpectra.setText(_translate("MainWindow", "Browse"))
        self.importScanButton.setText(_translate("MainWindow", "Import from Scan"))
        self.prefWLLabel.setText(_translate("MainWindow", "Preferred Wavelength"))
        self.WLList.setSortingEnabled(True)
        self.displayAllWLBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display all Wavelengths</p></body></html>"))
        self.displayAllWLBox.setText(_translate("MainWindow", "Cycle Wavelengths"))
        self.WLLabel.setText(_translate("MainWindow", "Wavelengths"))
        self.usvisibleBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ultrasound visible</p></body></html>"))
        self.usvisibleBox.setText(_translate("MainWindow", "Show Ultrasound"))
        self.addWL.setText(_translate("MainWindow", "+"))
        self.removeWL.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Acquisition"))
        self.groupBox_9.setTitle(_translate("MainWindow", "SFA"))
        self.label_12.setText(_translate("MainWindow", "SFA Max Averaged Frames"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>FRAMECORRTHRES</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "SFA Frame Threshold"))
        self.maxavgframes.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set to 1 to make SFA disapear.</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Snapshot Buffer Size"))
        self.groupBox_10.setTitle(_translate("MainWindow", "MSP"))
        self.unselectedLabel.setText(_translate("MainWindow", "Unselected"))
        self.selectedLabel.setText(_translate("MainWindow", "Selected"))
        self.unselectedList.setSortingEnabled(True)
        self.addButton.setToolTip(_translate("MainWindow", "Add Item"))
        self.addButton.setText(_translate("MainWindow", "--->"))
        self.selectedList.setSortingEnabled(True)
        self.deleteButton.setToolTip(_translate("MainWindow", "Remove Item"))
        self.deleteButton.setText(_translate("MainWindow", "<---"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Reconstruction"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>User Sound Trim</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Speed of Sound"))
        self.label_16.setText(_translate("MainWindow", "Filter Type"))
        self.invertReconstruction.setToolTip(_translate("MainWindow", "<html><head/><body><p>Introduced in 1.2.0.27 for more flexibility </p><p><span style=\" font-weight:600;\">ONLY USE IF YOU KNOW WHAT YOU ARE DOING</span></p></body></html>"))
        self.invertReconstruction.setText(_translate("MainWindow", "Invert Reconstruction"))
        self.backprojectionDerivative.setText(_translate("MainWindow", "Derivative"))
        self.backprojectionAuto.setText(_translate("MainWindow", "Auto"))
        self.label_17.setText(_translate("MainWindow", "Backprojection"))
        self.backprojectionDirect.setText(_translate("MainWindow", "Direct"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Depth Correction"))
        self.label_4.setText(_translate("MainWindow", "Background Oxygenation"))
        self.label_3.setText(_translate("MainWindow", "Background Absorption"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Processing"))
        self.groupBox_3.setTitle(_translate("MainWindow", "View Selection"))
        self.view1Button.setText(_translate("MainWindow", "Top Left"))
        self.view3Button.setText(_translate("MainWindow", "Bottom Left"))
        self.view2Button.setText(_translate("MainWindow", "Top Right"))
        self.view4Button.setText(_translate("MainWindow", "Bottom Right"))
        self.enableMultiPanel.setText(_translate("MainWindow", "enable MultiPanel"))
        self.groupBox.setTitle(_translate("MainWindow", "View Settings"))
        self.label_8.setText(_translate("MainWindow", "min"))
        self.label_7.setText(_translate("MainWindow", "Ultrasound Scaling"))
        self.autoScalingCheck.setText(_translate("MainWindow", "Auto Scaling"))
        self.label_10.setText(_translate("MainWindow", "Background Scaling"))
        self.bgmax.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.bgmin.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.fgmin.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Foreground Scaling"))
        self.fgmax.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.usmax.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p><p><br/></p></body></html>"))
        self.usmin.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">-1 = Minimum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">1 = Maximum of Image</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">0 = Scale from Zero,</span></p><p><span style=\" font-family:\'Verdana,sans-serif\'; font-size:12px; font-style:italic; color:#333333; background-color:#ffffdd;\">decimal value = Histogram Threshold</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "max"))
        self.bgwllabel.setText(_translate("MainWindow", "Background Wavelength"))
        self.bgWavelength.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Panels"))
        self.viewSpectraList.setSortingEnabled(True)
        self.groupBox_2.setTitle(_translate("MainWindow", "Layer Settings"))
        self.label_6.setText(_translate("MainWindow", "Palette Type"))
        self.transparentCheck.setText(_translate("MainWindow", "Transparency"))
        self.minLabel.setText(_translate("MainWindow", "Lower Threshold"))
        self.maxLabel.setText(_translate("MainWindow", "Upper Threshold"))
        self.visibleCheck.setText(_translate("MainWindow", "Visible"))
        self.logarithmicScalingCheck.setText(_translate("MainWindow", "Logarithmic Scaling"))
        self.loadCheck.setText(_translate("MainWindow", "Load"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Main Panel"))
        self.mainPanelPaletteType.setItemText(0, _translate("MainWindow", "DarkBlue"))
        self.mainPanelPaletteType.setItemText(1, _translate("MainWindow", "Bone"))
        self.mainPanelPaletteType.setItemText(2, _translate("MainWindow", "Contrast"))
        self.mainPanelPaletteType.setItemText(3, _translate("MainWindow", "Cyan"))
        self.mainPanelPaletteType.setItemText(4, _translate("MainWindow", "Gray"))
        self.mainPanelPaletteType.setItemText(5, _translate("MainWindow", "DarkGreen"))
        self.mainPanelPaletteType.setItemText(6, _translate("MainWindow", "Hot"))
        self.mainPanelPaletteType.setItemText(7, _translate("MainWindow", "Hue"))
        self.mainPanelPaletteType.setItemText(8, _translate("MainWindow", "Jet"))
        self.mainPanelPaletteType.setItemText(9, _translate("MainWindow", "LightBlue"))
        self.mainPanelPaletteType.setItemText(10, _translate("MainWindow", "LightGreen"))
        self.mainPanelPaletteType.setItemText(11, _translate("MainWindow", "LightRed"))
        self.mainPanelPaletteType.setItemText(12, _translate("MainWindow", "Magenta"))
        self.mainPanelPaletteType.setItemText(13, _translate("MainWindow", "DarkRed"))
        self.mainPanelPaletteType.setItemText(14, _translate("MainWindow", "RdBuBl"))
        self.mainPanelPaletteType.setItemText(15, _translate("MainWindow", "UnionJack"))
        self.mainPanelPaletteType.setItemText(16, _translate("MainWindow", "Yellow"))
        self.label_22.setText(_translate("MainWindow", "Background Contrast"))
        self.label_21.setText(_translate("MainWindow", "Background Brightness"))
        self.label_18.setText(_translate("MainWindow", "Background Colormap"))
        self.label_19.setText(_translate("MainWindow", "OPUS Contrast"))
        self.label_20.setText(_translate("MainWindow", "OPUS Brightness"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Visualization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRestrictions), _translate("MainWindow", "UI Locking"))
        self.groupBodyRegion.setTitle(_translate("MainWindow", "Scan Locations"))
        self.label_23.setText(_translate("MainWindow", "Scan locations available (each line one Region):"))
        self.groupBodyAtlas.setTitle(_translate("MainWindow", "Body Atlas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "BodyAtlas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

